### PR TITLE
Final Project Check-In 1

### PR DESCRIPTION
**Pull request by sambatipudi1**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Final_Project_check_in.rmd seems extra. Can it be deleted?

**Review by SidharthSaluja — COMMENTED** [review]
Okay now files looks good but I noticed name of the posts file is not proper. Could it be like Final_project_{YOUR NAME}_Checkin?

Can you do like that replace ur name with the name. This is to avoid merge conflicts. Render and submit me again

**Comment by SidharthSaluja** [comment]
Also can we have different name for csv file. I am getting merge conflicts

**Comment by sambatipudi1** [comment]
I have resolved the merge conflicts, could you please merge my dataset along with my Home work 2

**Review by SidharthSaluja — COMMENTED** [review]
Everything looks so good. Just name name of Final_Project_check_in_{Your name}
Add your name here. and render and commit

**Comment by sambatipudi1** [comment]
Hello Sidharth,

I have changed the name, could you accept my pull request please.

Do let me know if anymore changes are required.

Thanks and Regards,

Saisrinivas Ambatipudi

**Review by SidharthSaluja — APPROVED** [review]
All set. You are awsome

**Pull request merged**
