### PR TITLE
Final2_JerinJacob

### PR DESCRIPTION
**Pull request by jerin248486**
Final2

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
posts/_data/project_data 2.numbers 

Can you dont have a space between file names. Also double check the extension (just confirming is .numbers correct extension?)

**Comment by jerin248486** [comment]
I renamed the file without space and pushed but the change is not shown on GitHub! .numbers is the extension for spreadsheets on Mac. Actually, that file is not required for running my files. So deleting it won't make any difference on my works. Can I delete it on Github directly?

**Comment by jerin248486** [comment]
I renamed the file without space and pushed but the change is not shown on GitHub! .numbers is the extension for spreadsheets on Mac. Actually, that file is not required for running my files. So deleting it won't make any difference on my works. Can I delete it on Github directly?

**Comment by jerin248486** [comment]
Can you check if it is ok now? I think, now the file name has changed on GitHub too.

**Review by SidharthSaluja — APPROVED** [review]
All fine

**Pull request merged**
