### PR TITLE
Asch _Harwood_603 spring 2023

### PR DESCRIPTION
**Pull request by AschHarwood**
Asch Harwood, Homework 1 submission

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Did you sync the fork?

**Review by SidharthSaluja — COMMENTED** [review]
git_test.Rmd shouldn’t be present in post. Rest is all set

**Comment by AschHarwood** [comment]
sorry about that...do you want me to repush it?

**Review by SidharthSaluja — COMMENTED** [review]
Yep please do that

**Comment by SidharthSaluja** [comment]
Closing the comment for being open for a week. Schedule an appointment or slack in case you need help.

**Pull request closed without merging**
