### PR TITLE
Homework 1

### PR DESCRIPTION
**Pull request by zhou2447**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I need the freeze files too. Render qmd to get freeze files

**Comment by SidharthSaluja** [comment]
I know why this is case. It is because you uploaded freeze files via directly uploading to GitHub. This is bad idea bcs this way our .gitignore doesnt work. You would need to manually delete it from GitHub and then upload via Rstudio.  Slack me , I know how to do that. We can have call.

**Comment by zhou2447** [comment]
Thank you for letting me know that, I just uploaded via Github Desktop. Hope that works

**Review by SidharthSaluja — APPROVED** [review]
Looks fine to me

**Pull request merged**
