### PR TITLE
Submitting final project for Darron Bunt

### PR DESCRIPTION
**Pull request by dare-24**
Final project for Darron Bunt.

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I wanted your .qmd files in posts folder. Not the .csv files. .csv files should be in data folder.
Include the file posts/FPRedoneWithLog_DarronBunt.qmd and remove the .csv ones from posts

**Comment by dare-24** [comment]
...how do I remove the .csv ones?

**Review by SidharthSaluja — COMMENTED** [review]
In your post folder. Just delete manually .csv ones. And it will show in your git tab in R studio with D mark. Commit those charges and push it

**Review by SidharthSaluja — COMMENTED** [review]
In your post folder. Just delete manually .csv ones. And it will show in your git tab in R studio with D mark. Commit those charges and push it

**Review by SidharthSaluja — COMMENTED** [review]
In your post folder. Just delete manually .csv ones. And it will show in your git tab in R studio with D mark. Commit those charges and push it

**Comment by dare-24** [comment]
Ok; looking now the only thing in the "posts" folder is the .qmd so I think I (finally) did it correctly?

**Review by SidharthSaluja — APPROVED** [review]
Looks good

**Pull request merged**
