### PR TITLE
HW 1 Kristin Abijaoude

### PR DESCRIPTION
**Pull request by kabijaoude**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Can you include freeze folder too

**Comment by kabijaoude** [comment]
How do I include the freeze folder?

**Review by SidharthSaluja — COMMENTED** [review]
Ohhh I see. I think you might have not followed the instructions properly. qmd file should be made in the posts folder. Move that from _templates to posts. Render your qmd file in the posts folder to generate freeze files. I dont want _templates folder to be modified so please move that file.

Second could you correct the name of the qmd file (make it like Kristin_Abijaoude_HW1.qmd) instead of space in between

**Comment by kabijaoude** [comment]
sorry for the late reply. i changed the name and added the qmd file into the post in the freeze folder

**Comment by SidharthSaluja** [comment]
Did you add that to GitHub? I dont see them committed

**Comment by kabijaoude** [comment]
It's not letting me commit. Should I schedule an appointment to fix that?

**Comment by SidharthSaluja** [comment]
Thats strange if it is not letting you commit. Yes you can definitely make an appointment.

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
