### PR TITLE
HW1 submission

### PR DESCRIPTION
**Pull request by ttewks**
Submission for HW1

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Render your qmd file to generate freeze files and submit me freeze files

**Comment by ttewks** [comment]
I added the freeze files for HW1 and project #2. Please let me know if I did the process incorrectly and need to adjust

**Review by SidharthSaluja — COMMENTED** [review]
Cool I can see freeze files. But I didn’t receive your .qmd file for finalProject in posts folder

**Comment by ttewks** [comment]
Added the qmd, let me know if anything else is missing

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
