### PR TITLE
DACSS 603 HW3

### PR DESCRIPTION
**Pull request by lcollazo**
HW3 has been rendered and is ready for submission to the course blog. Thanks!

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Since you modified final check project. I again require freeze files for that

**Comment by lcollazo** [comment]
I made sure to commit the change to the final project after my pull request so it wouldn't be included. I am surprised to see it has been added. I only want to submit homework 3.

**Comment by SidharthSaluja** [comment]
In that case you need to revert back change from R studio and commit to GitHub so that GitHub doesnt have that change. If you want to modify final project then send me freeze files of that

**Comment by lcollazo** [comment]
Could you please provide details on how to do this? Also, could you please help me understand when I can commit my work? I want to be committing as I make progress so it's not possible to loose my work.

**Comment by SidharthSaluja** [comment]
Once you submit the pull request then after you commit anything. It will automatically show in the pull request until the request has been merged. So if you want to add anything you dont want me to submit, just dont commit to GitHub when ur pull request is open. So now what you have to do is - Save ur current file's data somewhere and from GitHub desktop revert back the change. Make sure  you verify from GitHub that the file you have modified have been back to normal. Now in local Rstudio you can paste ur modified file back and start working on final project. Dont commit to GitHub until I merge this pull request.

happy to do a meeting in case of doubt.

**Comment by lcollazo** [comment]
Thank you for sharing these steps. I think I have now correctly reverted my commit and homework 3 can now be posted.

**Review by SidharthSaluja — COMMENTED** [review]
You are awsome!

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
