### PR TITLE
Guanhua Tan's homework 1

### PR DESCRIPTION
**Pull request by TerenceGTan**

### CODE REVIEW

**Review by SidharthSaluja — APPROVED** [review]

**Review by SidharthSaluja — COMMENTED** [review]
Did you sync the fork?

**Comment by TerenceGTan** [comment]
I just created the new project today. I think it’s should be updated.

Guanhua

**Comment by SidharthSaluja** [comment]
I dont think so.  I see This branch is [2 commits ahead](https://github.com/TerenceGTan/603_Spring_2023/compare/DACSS:603_Spring_2023:template...template), [3 commits behind](https://github.com/TerenceGTan/603_Spring_2023/compare/template...DACSS:603_Spring_2023:template) DACSS:template. So you need to sync the fork, there is option to do that in the forked repo.

**Comment by TerenceGTan** [comment]
Hi, I did it. What’s next? Thank you!

Guanhua

**Pull request merged**
