### PR TITLE
Diana Rinker, HW1

### PR DESCRIPTION
**Pull request by diannnay**
pull request done with Prof Pang

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Umm a lot of unwanted files are there. 
1) README.md shouldn’t be modified. Please revert back the change.
2) posts/HW 1. diana Rinker .qmd should be deleted bcs I see another correct file in the posts folder.
3) site_libs folder should not be submitted me and should be deleted. Not sure how did you bypass our gitignore file.
4) I am getting merge conflicts. To fix this we need to delete the _freeze folder and render ur qmd files in the posts folder again to generate new _freeze files.


Other way to go about all this is saving all qmd files somewhere and  deleting the forked repo and creating a new one and then move all the saved files to posts folder and render it.
(I would do this method as my preferred method but both methods work and have to do carefully)

Please schedule an appointment in case you need help or want to do with me. Happy to help.

**Comment by diannnay** [comment]
> Umm a lot of unwanted files are there.
> 
> 1. README.md shouldn’t be modified. Please revert back the change.
> 2. posts/HW 1. diana Rinker .qmd should be deleted bcs I see another correct file in the posts folder.
> 3. site_libs folder should not be submitted me and should be deleted. Not sure how did you bypass our gitignore file.
> 4. I am getting merge conflicts. To fix this we need to delete the _freeze folder and render ur qmd files in the posts folder again to generate new _freeze files.
> 
> Other way to go about all this is saving all qmd files somewhere and deleting the forked repo and creating a new one and then move all the saved files to posts folder and render it. (I would do this method as my preferred method but both methods work and have to do carefully)
> 
> Please schedule an appointment in case you need help or want to do with me. Happy to help.

How could we schedule an appointment with you?

**Comment by diannnay** [comment]
Thank you for your feedback.  Could we schedule an appointment?

**Review by SidharthSaluja — COMMENTED** [review]
Definitely -

https://calendly.com/sidharthsalu/30min

**Pull request closed without merging**
