### PR TITLE
Abigail Balint Homework 1 committing

### PR DESCRIPTION
**Pull request by abbybalint**
Submitting pull request for Homework 1 Abigail Balint

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Could you give a better name for your image  like Abby_Balint_Image.jpeg to avoid merge conflicts. Also check if your image path is right in the about me file.

**Comment by abbybalint** [comment]
Let me know if this newest commit fixes it and if there are any other issues thank you!!

**Review by SidharthSaluja — COMMENTED** [review]
I see no changes in the image. I still see headshot.jpeg. Also somehow I am getting a merge conflict in the freeze files. Did you sync the fork?

**Comment by abbybalint** [comment]
I just synced my repo fork and then committed my changes again. It's rendering properly now for me. My homework 1 is rendering as well. Hopefully these changes work. Thanks!

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
