### PR TITLE
Derian-Toth_M HW1

### PR DESCRIPTION
**Pull request by mderiantoth**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
I need the freeze files too. Render your qmd file

**Comment by mderiantoth** [comment]
> I need the freeze files too. Render your qmd file

I rendered, but am not sure how to send you the freeze files. I just sent a pull request for the rmd and html files. Hopefully that is what you need(?)

I think I figured out the issue. I have an rmd file because I wrote the code using an rmarkdown document. I got stuck with the professors instructions to make a copy of her document in github. I don't see where I can "save as" on the HW 1 template.

**Review by SidharthSaluja — COMMENTED** [review]
First of all it should be qmd file instead of rmd file. If you render and if you still get html file. You might need to download quarto and then render. https://quarto.org/docs/get-started/

**Comment by mderiantoth** [comment]
Okay I think I figured it out! Let me know if I still need to make changes. 

Thank you for your patience with me on this!

**Review by SidharthSaluja — COMMENTED** [review]
Um still I cant see freeze files and posts/DerianToth_M_HW1.Rmd and html file should be removed. Only qmd file in the post should be there along with Freeze folders. Schedule a meeting with me in case of isssues

**Review by SidharthSaluja — COMMENTED** [review]
Yeah now only freeze file is missing. Rendering would make freeze folders.

**Comment by mderiantoth** [comment]
I couldn't upload full folders, but there was a folder created with the visualizations in it. Is that what you are looking for? If not I will schedule a meeting with you to discuss tomorrow

**Review by SidharthSaluja — COMMENTED** [review]
The folder should start with _freeze/

**Comment by mderiantoth** [comment]
And it should be in the same place as my qmd file in my computer?

**Review by SidharthSaluja — COMMENTED** [review]
Nope it should be in your main folder. It would be outside posts.

**Comment by mderiantoth** [comment]
Okay, I don't see it in my Git branch or on my computer. Can I schedule a meeting with you for tomorrow?

**Review by SidharthSaluja — COMMENTED** [review]
Ofcourse you can !

**Pull request closed without merging**
