### PR TITLE
Final 1

### PR DESCRIPTION
**Pull request by Cassie199**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Everything looks good but can you rename posts file to may be Xiaoyan_Final_project to avoid merge conflicts? and render again.

**Review by SidharthSaluja — COMMENTED** [review]
site_libs folder seems unwanted. Can it be deleted?

**Comment by Cassie199** [comment]
modified files and HW2

**Review by SidharthSaluja — COMMENTED** [review]
Everything looks awesome now. But I see posts/FinalProj_1.qmd extra. Can this be deleted too. Also can you have better name for .xlsx data?

**Comment by Cassie199** [comment]
modified names

**Review by SidharthSaluja — APPROVED** [review]
You are awsome

**Pull request merged**
