### PR TITLE
Homework 1 Pull Request_MDT

### PR DESCRIPTION
**Pull request by mderiantoth**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Not sure why you are getting site_libs folder. When we didn’t the zoom call, we didnt have that. We had proper format on zoom call. I just want freeze and qmd. Also why did you move DerianToth_M_HW1 from posts folder. I need that in the posts folder. Fix these things and  commit me changes.

**Comment by mderiantoth** [comment]
I did not move anything. What I am doing is uploading the documents from my computer into my branch. Is there a different way I should be getting the files?

**Comment by mderiantoth** [comment]
I uploaded the file into the posts folder, and I see the Freeze folder in my branch, is it not where you need it to be?

**Review by SidharthSaluja — COMMENTED** [review]
It is in good shape now. I see site_libs folder, I thought gitignore ignored it but in your case it displayed so thats pretty strange.
could you do me a favor delete the _freeze folders and just render your challenge file in post again and send me new freeze files.

**Comment by SidharthSaluja** [comment]
I know why this is case. It is because you uploaded freeze files via directly uploading to GitHub. This is bad idea bcs this way our .gitignore doesnt work. You would need to manually delete it from GitHub and then upload via Rstudio. You might have to do git pull to sync R studio and GitHub. Slack me , I know how to do that. We can have call.

**Comment by mderiantoth** [comment]
Are there instructions in the google classroom somewhere that I missed? I watched the loom video and that has you uploading the documents manually like I did. But I seem to be the only one having issues so I am guessing I missed something somewhere.

**Comment by mderiantoth** [comment]
I deleted the original documents (including the freeze folder) from Github. Then I followed these instructions that I found online: 
1. Commit and push the changes to GitHub
2. In RStudio click the Git tab in the upper right pane.
3. Click Commit .
4. In the Review changes view, check the staged box for all files.
5. Add a commit message, for example Add initial speed and distance report .
6. Click Commit .

And then resubmitted the pull request. How does it look now?

**Review by SidharthSaluja — APPROVED** [review]
Looks awesome now!

**Comment by mderiantoth** [comment]
yay!!! Do you need anything else or is it set now?

**Pull request merged**
