### PR TITLE
Uploading hw2

### PR DESCRIPTION
**Pull request by hrosenbaum**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Please render your file to generate _freeze files. 
It may be because of yaml header. Check your yaml header from _templates/PostsTemplate for how should YAML header look like

**Comment by SidharthSaluja** [comment]
Nope didnt receive your freeze files. I instead received a copy of hw2 which was not needed. But the yaml in the copied version looks GOOD. 
So I would say copy paste the yaml header (just like you had in your copied version) into the original file hw2 and finalproject. And delete copied version of hw2 because I dont need that. Then just hit render in R studio. This will generate _freeze files and commit those freeze folder.

Please ask if confused.

**Comment by hrosenbaum** [comment]
So does just homework 2 need that? I’m having problems with this.

**Review by SidharthSaluja — APPROVED** [review]
I know you are awsome and will do it nicely

**Pull request merged**
