### PR TITLE
OMurphy HW1 Commit

### PR DESCRIPTION
**Pull request by olimurphy**

### CODE REVIEW

**Comment by SidharthSaluja** [comment]
Why you deleted that?

**Comment by olimurphy** [comment]
Hi!
I'm guessing this means that I didn't do the commit right? I'm having
trouble understanding what is going on with git and I apologize if it
caused any problems/deleted something unintentionally.
Ollie

**Comment by SidharthSaluja** [comment]
I see a file from _templates being deleted -  HWtemplate_RosemaryPang.qmd. _templates folder shouldn’t be modified.

**Comment by olimurphy** [comment]
I think that I overwrote it on my computer rather than saving as, but I
can't figure out how to get the file back on my end so that I can correct
it. Is there a way to just download that file so that I can put it into the
folder on my end? Or do I need to re-fork the branch? Or something else?
Sorry--I haven't used git much before and I'm a bit out of my depth.
Thanks,
Ollie

**Comment by olimurphy** [comment]
I think I figured it out, and submitted another request. Please let me know
if there are any more issues.
Ollie

**Pull request closed without merging**
