### PR TITLE
HW_5_Diana_Rinker

### PR DESCRIPTION
**Pull request by diannnay**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Need freeze files for checkin3, checkin54, hw3.

**Comment by diannnay** [comment]
> Need freeze files for checkin3, checkin54, hw3.
I am only submitting  hw5, other files don't need an upload...

**Comment by diannnay** [comment]
I just removed check-in 3 and 4 out of the project. But I need to keep  check-in 5, because R keeps loosing my progress and thats is how I save backup..

**Review by SidharthSaluja — COMMENTED** [review]
I see you are submitting me checkin 3, checkin 4, checkin 5, hw3, and hw5. 
Whatever you dont want me to submit, Can you please delete that from GitHub. You can store backup in your local machine. But if you store on GitHub, I will receive ur submissions. Bcs the pull request will try to pull everything from your repo. 

Whatever you want to submit me, please keep in mind to submit freeze files along with that

Happy to schedule a meeting through calendy in case of trouble - https://calendly.com/sidharthsalu/

**Review by SidharthSaluja — COMMENTED** [review]
Freeze files of checkin 3, 4 and hw3 is still missing

**Review by SidharthSaluja — COMMENTED** [review]
Awsome I just need freeze files for hw3. Rest looks fine

**Review by SidharthSaluja — APPROVED** [review]
You are awsome!!!

**Pull request merged**
