### PR TITLE
Homework 1 - Commit - Christine Brydges

### PR DESCRIPTION
**Pull request by cmbrydges**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Need freeze files instead of the html file. Not sure why you getting html files. Could you slack me or book appointment with me

**Comment by cmbrydges** [comment]
@SidharthSaluja I had both an .html file (From rendering it) and a .qmd file - Is the .qmd file not being seen there?

I am 100% new to committing so do not quite understand - what are "freeze files"?

**Comment by SidharthSaluja** [comment]
This is so strange. Qmd file is okay. But .html file should not be generated. When you render it, freeze files should be generated.

**Comment by cmbrydges** [comment]
I do not know what a freeze file is - I see .qmd in my _templates folder and no .html now - What else should I be doing?

**Comment by cmbrydges** [comment]
This is what I see on the branch I am trying to push
Screen Shot 2023-02-28 at 7 29 03 PM

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
