### PR TITLE
DACSS 603 Homework 1 

### PR DESCRIPTION
**Pull request by lcollazo**
DACSS 603 Homework 1 for Laura Collazo

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
The folders dacs603hw_lauraCollazo_files and dacss_603_homework_1_files are not requrired. Kindly remove them. The files in the posts folder are fine except HWtemplate_RosemaryPang. The instructor would put that file in posts when she desires. So only dacss601hw1_LauraCollazo.qmd file should be in the posts. Could you please run this qmd file to generate freeze files and commit those freeze files for better rendering on our side.

**Comment by lcollazo** [comment]
Hi @SidharthSaluja, I was concerned some of these commits that were made would cause an issue which is why I reached out via email before submitting the pull request. I was receiving different error messages when trying to commit the right file and in trying to troubleshoot I ended up commiting other files. I'm unsure how to remove these commits I don't want and don't know enough about Git yet to resolve on my own. I'm also unsure about the HWtemplate showing in posts. I see this in my repo, so I must have commited it without realizing it. In my directory it shows under templates, though, not posts. Is there a way to just wipe all my commits and start over?

**Comment by SidharthSaluja** [comment]
Yea, the screenshot in the email didn’t show me what files were there. I took closer look and felt some files are extra. Please make an appointment if you don't know how to delete files and commit those changes. You don't need to wipe out everything. Just deleting the files should work. Slack me for appointment.

**Comment by SidharthSaluja** [comment]
Closing this to avoid merge conflicts. Please submit a new pull request

**Pull request closed without merging**
