### PR TITLE
Rowley - Homework 1

### PR DESCRIPTION
**Pull request by cerowley**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Could you do me some favors
1) Rename your file to Rowley_Homework_1.qmd to eliminate space
2) Could you delete freeze folder from your side and render your Rowley_Homework_1 file again to generate new freeze files. 

I am seeing merge conflicts from _freeze/posts/HWtemplate_RosemaryPang. We can fix this if you follow above steps.

**Comment by cerowley** [comment]
Hi Sidarth,

I hope you're well.

Thank you so much for your instructions - I believe my pull request should be all set now. Please let me know if I need to do anything else.

Thank you again!

Caitlin


Caitlin Rowley (she/her)

Research Analyst

Applied Research and Program Evaluation

Donahue Institute
UMass Amherst
333 South Street, Suite 400
Shrewsbury, MA 01545
774-455-7608
www.donahue.umass.edu<https://www.donahue.umass.edu/>


[A picture containing text, sign, tableware, plate  Description automatically generated]

________________________________

**Review by SidharthSaluja — COMMENTED** [review]
I dont think you followed instructions exactly because I am still seeing merge conflicts. In the submitted files of posts folder, I now see two files, one of them should be deleted. Secondly, I dont think you deleted the whole freeze folder and rendered qmd file again. You might have done in R studio but forgot to commit to GitHub. You would see a D mark when file is deleted in git window, you need to commit that too. Schedule an appointment in case you need help

**Comment by cerowley** [comment]
Hi Sidharth,

First, I apologize for misspelling your name in my first email. I also apologize for not resolving the merge issue! I actually no longer see a freeze folder in GitHub after I render - do you have any guidance?

Thank you again!

Caitlin


Caitlin Rowley (she/her)

Research Analyst

Applied Research and Program Evaluation

Donahue Institute
UMass Amherst
333 South Street, Suite 400
Shrewsbury, MA 01545
774-455-7608
www.donahue.umass.edu<https://www.donahue.umass.edu/>


[A picture containing text, sign, tableware, plate  Description automatically generated]

________________________________

**Review by SidharthSaluja — COMMENTED** [review]
I can definitely help you. Could you please schedule a meeting with me or slack me. We need to fix unwanted files and freeze files merge conflict

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
