### PR TITLE
final checkin 3

### PR DESCRIPTION
**Pull request by saipadma27**

### CODE REVIEW

**Review by SidharthSaluja — COMMENTED** [review]
Could you rename your file as finalCheck3_{Yourname}.qmd. I might not have noticed that earlier but this needs to be fixed. Please render again and send me .qmd and freeze

**Comment by saipadma27** [comment]
@SidharthSaluja Hey I changed the file name. Let me know if anything is needed

**Review by SidharthSaluja — COMMENTED** [review]
Just remove this final_checkIn3.qmd

**Comment by saipadma27** [comment]
How should I remove it ?

**Review by SidharthSaluja — COMMENTED** [review]
In your R studio, you can select the file and delete it (or you can delete from file manager in your computer). In the git tab it will show a D mark. so commit that change.

**Comment by saipadma27** [comment]
I just renamed the file so I don't have that file in my laptop

**Comment by SidharthSaluja** [comment]
If you dont push the changes how will I get your changes?

**Comment by saipadma27** [comment]
I pushed

**Comment by saipadma27** [comment]
Did you get what changes I made ?

**Review by SidharthSaluja — APPROVED** [review]

**Pull request merged**
